name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the Flutter web app
      - name: Build Flutter web app
        run: flutter build web

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch you want to deploy to (default is gh-pages)
          folder: build/web  # The folder containing the web app (flutter build web)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}