name: GitHub Page Deploy

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '17'
          distribution: 'zulu'

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Install dependencies
      - run: flutter pub get

      # Build the app
      - name: Build the webapp
        run: flutter build web

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/web  # The folder containing the web app (flutter build web)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
