name: Flutter Release

on:
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Install Java 17 using Zulu OpenJDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # Set up Flutter (use version 3.24.5)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Install dependencies
      - run: flutter pub get

      # Get the latest Git tag
      - name: Get Latest Git Tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")  # Fallback if no tags are found
          echo "Latest tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV  # Write to environment file

      # Increment the version
      - name: Increment Version
        id: increment_version
        run: |
          VERSION_TAG=${{ env.TAG }}
          VERSION_NUMBER=${VERSION_TAG:1}  # Remove the 'v' prefix
          VERSION_PARTS=(${VERSION_NUMBER//./ })  # Split into array based on '.'
          PATCH_VERSION=${VERSION_PARTS[2]}
          PATCH_VERSION=$((PATCH_VERSION + 1))  # Increment patch version
          NEW_VERSION="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
          echo "New Version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV  # Write to environment file

      # Build the app
      - name: Build the app
        run: flutter build apk --release --build-name ${{ env.NEW_VERSION }} --build-number $(( $GITHUB_RUN_NUMBER + 1 ))     

      # Rename APK
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Next\ Bus.apk

      # Verify APK Exists
      - name: Verify APK Path
        run: |
          echo "Checking APK location:"
          ls -la build/app/outputs/flutter-apk/

      # Push New Tag
      - name: Push New Tag
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          draft: false
          prerelease: false

      # Upload APK to Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/Next\ Bus.apk
          asset_name: Next\ Bus.apk
          asset_content_type: application/vnd.android.package-archive