name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subhedar/flutter-action@v2
        with:
          flutter-version: 'latest'

      - run: flutter pub get

      - name: Determine Next Version
        uses: actions/version@v3
        with:
          major-version: 1
          minor-version: 0
          patch-version: 0

      - name: Build the app
        run: flutter build apk --release --version-name ${{ steps.determine-next-version.outputs.VERSION }} --version-code ${{ steps.determine-next-version.outputs.BUILD_VERSION }}

      - name: Upload APK to GitHub Release
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/release/app-release.apk

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.determine-next-version.outputs.VERSION }}
          release_name: Release v${{ steps.determine-next-version.outputs.VERSION }}
          draft: false
          prerelease: false
