name: Save WebApp to web-deploy Branch

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '17'
          distribution: 'zulu'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the app
      - name: Build the webapp
        run: flutter build web

      # Deploy to the web-deploy branch
      - name: Deploy to web-deploy branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Check if the branch exists
          if git ls-remote --exit-code --heads origin web-deploy; then
            echo "Branch 'web-deploy' exists, checking it out."
            git checkout web-deploy
          else
            echo "Branch 'web-deploy' does not exist, creating it."
            git checkout -b web-deploy
          fi

          # Add build files and commit
          cp -r build/web/* . # Move files to the root directory
          git add .
          git commit -m "Deploy webapp to web-deploy branch"

          # Push changes
          git push origin web-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
